// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82fREUU1OR9oYCy6sEYSR9n2Hilv_3LQ',
    appId: '1:566338279940:web:6a33625a4eabc4c9617351',
    messagingSenderId: '566338279940',
    projectId: 'cognize-783b6',
    authDomain: 'cognize-783b6.firebaseapp.com',
    storageBucket: 'cognize-783b6.appspot.com',
    measurementId: 'G-NSKP691V0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZApvC8ZxKMEAPC2mghWHuyKh0L--HfPg',
    appId: '1:566338279940:android:a6228a0c162fceba617351',
    messagingSenderId: '566338279940',
    projectId: 'cognize-783b6',
    storageBucket: 'cognize-783b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVC2aZPlz8LWakg2iSspMcVTCfVBm7LY',
    appId: '1:566338279940:ios:844d40acaaf968dc617351',
    messagingSenderId: '566338279940',
    projectId: 'cognize-783b6',
    storageBucket: 'cognize-783b6.appspot.com',
    iosClientId:
        '566338279940-eq486r1uj4u0b75h1aipq0q1b1u3ou53.apps.googleusercontent.com',
    iosBundleId: 'com.jorahty.cognize',
  );
}
